spring:
  application:
    name: stakes-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/stakes_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:gustavo232002}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 20
        format_sql: false

logging:
  level:
    root: WARN
    com.stakes: INFO

server:
  port: ${PORT:8080}





